### ISSUE TITLE
在uni-app项目中使用后store action中打印this.data异常

### ISSUE THREAD

**Issue by mlzk** [Allen-1998/pinia-auto-refs#2]
store/app.ts
定义
export default defineStore({
  id: 'app',
  state: () => {
    return {
      systemInfo: {},
      appName:'a',
    } 
  },
  actions: {
    getSystemInfo() {
		console.error(this.appName)
      if (Object.keys(this.systemInfo).length) return this.systemInfo
      const systemInfo = uni.getSystemInfoSync()
      Object.assign(this.systemInfo, systemInfo)
      return systemInfo
    },
  },
})

getSystemInfo()执行 console.error(this.appName)
期望结果：'a'
通过import（pinia推荐）引用结果：'a'
使用pinia-auto-refs 配置之后使用结果：

{
    "_object": {
        "systemInfo": {
            "SDKVersion": "",
            "appLanguage": "zh-Hans",
            "appVersion": "13.6.18",
          //...
        },
        "appName": "a"
    },
    "_key": "appName",
    "__v_isRef": true
}

老铁知道我这哪搞得不对了么

**Comment by Allen-1998** [comment]
无法复现，辛苦建立一个最小复现的仓库方便排查问题

**Comment by dmskys** [comment]
我也出现这个问题，发现定义的state属性，在action中无法通过this.attr=xx赋值，发现所有的state的属性变成了ref对象了
请作者参考参考如下代码：
```
export default defineStore({
  id: 'test',
  persist: {
    // 开启持久化
    enabled: true,
    H5Storage: window?.localStorage,
    strategies: [
      {
        key: 'test',
        storage: window?.sessionStorage,
      },
    ],
  },
  state: () => {
    return {
      name: '张三',
      token: 'token...',
    }
  },
  getters: {
    fullName: (state) => {
      console.log(state.name)
      return state.name + '丰'
    },
  },
  actions: {
    updateName(name: string) {
      console.log('changeName')
      //定义的变量，全部变成ref了，必须通过.value赋值和取值，并且vscode的.value标红
      this.name.value = name
      console.log('this:', this)
    },
    getName() {
      return this.name.value
    },
  },
})
```
在微信小程序中查看，h5没有问题，虽然这样可以，但还是想通过this.name=name赋值和this.name返回值
具体参考项目可查看这个 git项目：https://github.com/ttk-cli/uni-vue3-vite-ts-pinia 的将他的test store 改成我的代码，并在test.vue 配置点击事件调用
 ```
 <view @click="changeName">changeName</view>
<view @click="getName">getName</view>

function changeName() {
  const testStore = useStore('test')
  testStore.updateName('myname')
}

function getName() {
  const testStore = useStore('test')
  console.log(testStore.getName())
  console.log(testStore.fullName.value)
}
```

已发现问题：
调用方式错误因使用下面方式调用：
```
  const {updateName}= useStore('test')
  updateName('myname')
const {getName,fullName}= useStore('test')
 console.log(getName())
  console.log(fullName)
```

**Comment by Allen-1998** [comment]
> 

无法复现，同时模版项目[uni-vue3-vite-ts-pinia](https://github.com/ttk-cli/uni-vue3-vite-ts-pinia)已更新整体依赖至新版本，可以重新拉取再试一下～

**Comment by HeHong1** [comment]
我也出现这个问题，在action中使用this赋值，没有效果，打印出来的state是ref对象，赋值都赋值到了ref层上

**Comment by dmskys** [comment]
> 我也出现这个问题，在action中使用this赋值，没有效果，打印出来的state是ref对象，赋值都赋值到了ref层上

调用方式错误，应该这么调用 ：
  const {updateName}= useStore('test')
  updateName('myname')
const {getName,fullName}= useStore('test')
 console.log(getName())
  console.log(fullName)

**Comment by HeHong1** [comment]
> 



> 

useStore('test').fullName直接取值这种写法是错误的吗？
